### PR TITLE
chore(view): add (missing) message field in samples.

### PR DESCRIPTION
**Pull request by ytaek**
@jejecrunch 님이 요청해주셨던, message field 빠진 부분 채워서 다시 넣었습니다 : -)

### CODE REVIEW

**Comment by hy57in** [comment]
@all-contributors please add @ansrlm  for code

**Comment by kmin-jeong** [comment]
@all-contributors please add @kmin-jeong for code

**Comment by hy57in** [comment]
https://github.com/all-contributors please add @hy57in  for code

**Comment by hanseul-lee** [comment]
https://github.com/all-contributors please add @ansrlm for code

**Review by kmin-jeong — APPROVED** [review]
메세지 부분 확인했습니다!

**Review by hanseul-lee — APPROVED** [review]
LGTM~!

**Comment by hy57in** [comment]
@all-contributors please add @hy57in  for code

**Review by ansrlm — APPROVED** [review]
LGTM!!

**Comment by anpaul0615** [comment]
https://github.com/all-contributors please add @anpaul0615  for code

**Comment by ooooorobo** [comment]
@all-contributors please add @ooooorobo for code

**Comment by hanseul-lee** [comment]
@all-contributors please add @hanseul-lee  for code

**Comment by anpaul0615** [comment]
@all-contributors please add @anpaul0615  for code

**Comment by jin-Pro** [comment]
https://github.com/all-contributors please add @jin-Pro for code

**Comment by jin-Pro** [comment]
@all-contributors please add @jin-Pro for code

**Comment by inthejim** [comment]
https://github.com/all-contributors please add @inthejim for code

**Pull request merged**
